[package]
name = "db2md"
author = "Sizhe Liu"
email = "sizhe.liu@fit-foxconn.com"
license = "TBA"
version = "0.1.0"
edition = "2021"

[dependencies]
calamine = "0.26.1"
iced = { version = "0.13.1", default-features = false }
rfd = "0.15.0"
yaml-rust2 = "0.9.0"
